# Generated by Django 5.1.6 on 2025-02-14 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather_Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('uv_index', models.IntegerField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('light_intensity', models.IntegerField(blank=True, null=True)),
                ('rain_mm', models.FloatField(blank=True, null=True)),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.day')),
                ('Weather_Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weather_station')),
            ],
            options={
                'unique_together': {('Weather_Station', 'Day', 'timestamp')},
            },
        ),
    ]
