# Generated by Django 5.1.6 on 2025-02-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_station',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
