# Generated by Django 5.1.6 on 2025-02-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_weather_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_station',
            name='location',
            field=models.CharField(default='unknow location', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='observacao',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather_station',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather_station',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
